name: advent_of_code_2022
description: Solutions for Advent of Code 2022.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
