name: advent_of_code_2022
description: Solutions for Advent of Code 2022.
version: 0.0.1

environment:
  sdk: "^3.8.0"

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
