name: advent_of_code_2022
description: Solutions for Advent of Code 2022.
version: 0.0.1

environment:
  sdk: "^3.7.0"

dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
