name: advent_of_code_2022
description: Solutions for Advent of Code 2022.
version: 0.0.1

environment:
  sdk: "^3.0.0"

dependencies:
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
